### ISSUE TITLE
SAS ender 5 + zero g

### ISSUE THREAD

**Issue by Hobbss27** [ZeroGDesign/UserMods#19]
i have been preparing to install this system and with the new update the duct seems to not line up fully.
![image](https://user-images.githubusercontent.com/120603946/207721913-e69283b9-7dc7-4397-864a-f67bfaada09a.png)

also the mounting system will not work with my setup on the sides. it will work in the back( would be rather far) but i would rather have 1 per side. i plan to modify your mount to fit my printer. but as a reference with a stock bed.
![image](https://user-images.githubusercontent.com/120603946/207723183-8ba0564a-24c5-4035-99f4-629fcfd00cec.png)
![image](https://user-images.githubusercontent.com/120603946/207723218-af9fc275-4e54-46d1-b613-de46777371b7.png)
![image](https://user-images.githubusercontent.com/120603946/207723259-86718215-62aa-479e-a175-75d12d6065b4.png)
![image](https://user-images.githubusercontent.com/120603946/207723320-ee9b0a4a-13af-45f6-b420-e206420a6055.png)

**Comment by nelsongraca** [comment]
stale

**Comment by nelsongraca** [comment]
stale
